import { DEPLOYMENT_PACKAGE_ARCHIVE_NAME,
  DEPLOYMENT_PACKAGE_RUNTIME,
  DEPLOYMENT_PACKAGE_HANDLER 
} from "../constants/lambdaDeploymentPackage.mjs";

export const REHYDRATION_LAMBDA_PARAMS = {
  Code: {
    S3Bucket: process.env.LAMBDA_DEPLOYMENT_PACKAGE_S3_BUCKET_NAME,
    S3Key: DEPLOYMENT_PACKAGE_ARCHIVE_NAME
  },
  FunctionName: process.env.REHYDRATION_LAMBDA_NAME,
  Role: process.env.LAMBDA_EXECUTION_ROLE_ARN,
  Runtime: DEPLOYMENT_PACKAGE_RUNTIME,
  Handler: DEPLOYMENT_PACKAGE_HANDLER
}